global: {}

ibm-cp4i-operators:
  subscriptions:
    cloudpakforintegration:
      name: ibm-cp-integration
      subscription:
        channel: v7.3-sc2
        installPlanApproval: Automatic
        name: ibm-common-service-operator
        source: opencloud-operators
        sourceNamespace: openshift-marketplace
        