global: {}

ibm-catalogs:
  catalogs:
    commonservices:
      name: opencloud-operators
      catalog:
        displayName: IBMCS Operators
        publisher: IBM
        sourceType: grpc
        image: icr.io/cpopen/ibm-common-service-catalog@sha256:4d745bf5a8d6cf10f0fbd702ea5f5f37d75e9fe4026bc2215515c4db0400f570
        updateStrategy:
          registryPoll:
            interval: 45m

    ibmoperators:
      name: ibm-operator-catalog
      catalog:
        displayName: "IBM Operator Catalog"
        publisher: IBM
        sourceType: grpc
        image: icr.io/cpopen/ibm-operator-catalog:latest
        updateStrategy:
          registryPoll:
            interval: 45m